#app
server:
  port: 8082
  servlet:
    context-path: /bluewhale

#开启热部署
spring:
  devtools:
    restart:
      enabled: false

---
#静态资源路径设置
spring:
  mvc:
    static-path-pattern: /**
    favicon:
      enabled: true
  resources:
    #这里修改静态资源访问路径为classpath:/，原来为classpath:/static/
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/, classpath:/templates/

  #文件上传
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

---
#freemarker模版配置
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates
    request-context-attribute: request
    settings:
      template_update_delay: 0

---
#数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bw
    #    url: jdbc:mysql://119.3.78.155:3306/blueWhale
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver


#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.qs.bluewhale.entity
  typeEnumsPackage: com.qs.bluewhale.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    com.qs.bluewhale.mapper: debug